In [ ]:
import numpy as np


Array

In [ ]:
# Create a rank 1 array
a = np.array([0, 1, 2])
print(type(a))


<class 'numpy.ndarray'>


In [ ]:
# this will print the dimension of the array
print(a.shape)
print(a[0])
print(a[1])
print(a[2])


(3,)
0
1
2


In [ ]:
# Change an element of the array
a[0] = 5
print(a)


[5 1 2]


In [ ]:
# Create a rank 2 array
b = np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


Creating NumPy Array

In [ ]:
# Create a 3x3 array of all zeros
a = np.zeros((3,3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create a 2x2 array of all ones
b = np.ones((2,2))
print(b)


[[1. 1.]
 [1. 1.]]


In [ ]:
# Create a 3x3 constant array
c = np.full((3,3), 7)
print(c)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Create a 3x3 array filled with random values
d = np.random.random((3,3))
print(d)


[[0.98802641 0.01812241 0.27001425]
 [0.30250822 0.54257635 0.24740239]
 [0.12007268 0.68157128 0.27299814]]


In [ ]:

# Create a 3x3 identity matrix
e = np.eye(3)
print(e)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:

# convert list to array
f = np.array([2, 3, 1, 0])
print(f)


[2 3 1 0]


In [ ]:

# arange() will create arrays with regularly incrementing values
g = np.arange(20)
print(g)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:

# note mix of tuple and lists
h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)


[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [ ]:

# create an array of range with float data type
i = np.arange(1, 8, dtype=np.float64)
print(i)


[1. 2. 3. 4. 5. 6. 7.]


In [ ]:

# linspace() will create arrays with a specified number of items which are
# spaced equally between the specified beginning and end values j= np.linspace(start, stop, num)
j = np.linspace(2, 4, 5)
print(j)

[2.  2.5 3.  3.5 4. ]


Data Types

In [ ]:
# Let numpy choose the datatype
x = np.array([0, 1])
y = np.array([2.0, 3.0])


In [ ]:

# Force a particular datatype
z = np.array([5, 6], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


Array Indexing

In [ ]:
# An exemplar array
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])


In [ ]:

# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)


Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [ ]:

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)



Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]


In [ ]:

# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


Basic array operations

In [ ]:
a = np.array([1, 2, 5, 3])



In [ ]:
# add 1 to every element
print ("Adding 1 to every element:", a+1)


Adding 1 to every element: [2 3 6 4]


In [ ]:
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)


Subtracting 3 from each element: [-2 -1  2  0]


In [ ]:
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)


Multiplying each element by 10: [10 20 50 30]


In [ ]:
# square each element
print ("Squaring each element:", a**2)


Squaring each element: [ 1  4 25  9]


In [ ]:
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)


Doubled each element of original array: [ 2  4 10  6]


In [ ]:
# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


unary operators in numpy

In [ ]:

arr = np.array([[1, 5, 6],
[4, 7, 2],
[3, 1, 9]])


In [ ]:

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))


Largest element is: 9
Row-wise maximum elements: [6 7 9]


In [ ]:

# minimum element of array
print ("Column-wise minimum elements:",arr.min(axis = 0))


Column-wise minimum elements: [1 1 2]


In [ ]:
# sum of array elements
print ("Sum of all array elements:",arr.sum())


Sum of all array elements: 38


In [ ]:
# cumulative sum along each row
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


Binary operators

In [ ]:
# binary operators in Numpy

a = np.array([[1, 2],
[3, 4]])
b = np.array([[4, 3],
[2, 1]])


In [ ]:

# add arrays
print ("Array sum:\n", a + b)


Array sum:
 [[5 5]
 [5 5]]


In [ ]:

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)


Array multiplication:
 [[4 6]
 [6 4]]


In [ ]:

# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Matrix multiplication:
 [[ 8  5]
 [20 13]]


Universal functions (ufunc)

In [ ]:


# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))


Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))


Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]


In [ ]:

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Square root of array elements: [0.         1.         1.41421356 1.73205081]


Matrix inverse

In [ ]:
#simple python program to find the inverse of an array (without exception handling)
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

Linear Algebra using NumPy: (Few in-built functions)

In [ ]:
#Matrix and Vector Product
dot(a, b[, out])  #Dot product of two arrays.
linalg.multi_dot(arrays) #Compute the dot product of two or more arrays in a single function
                          #call, while automatically selecting the fastest evaluation order.

vdot(a, b) #Return the dot product of two vectors.
inner(a, b) #Inner product of two arrays.
outer(a, b[, out]) #Compute the outer product of two vectors.

matmul(x1, x2, /[, out, casting, order, ...])  #Matrix product of two arrays.
tensordot(a, b[, axes]) #Compute tensor dot product along specified axes for arrays >= 1-D.

einsum(subscripts, *operands[, out, dtype, ...]) # Evaluates the Einstein summation convention on the operands.
einsum_path(subscripts, *operands[, optimize]) #Evaluates the lowest cost contraction order for an einsum expression by considering the creation of intermediate arrays.

linalg.matrix_power(a, n) #Raise a square matrix to the (integer) power n.

#Matrix Eigen Values
linalg.eig(a) #Compute the eigenvalues and right eigenvectors of a square array.
linalg.eigh(a[, UPLO]) #Return the eigenvalues and eigenvectors of a complex Hermitian (conjugate symmetric) or a real symmetric matrix.
linalg.eigvals(a) #Compute the eigenvalues of a general matrix.

SyntaxError: invalid syntax (<ipython-input-49-f2bd0acdbe88>, line 2)